interface tyBuilding {
    num:string,
    xh:string,
    floor:string,
    botlevel:string,
    height:string,
    beamstd:string,
    slabstd:string,
    colstd:string,
    wallstd:string,
}
interface tybeam {
    num:string,
    xh:string,
    std:string,
    name:string,
    width:string,
    size:string,
    startx:string,
    starty:string,
    startz:string,
    endx:string,
    endy:string,
    endz:string,
    gjlx:string,
}
interface tyslab {
    x:string,
    y:string,
    l:string,
    b:string,
    h:string,
    r:string,
    level:string,
}
interface tycolumn {
    num:string,
    xh:string,
    std:string,
    name:string,
    local:string,
    jiaodian:string,
}
interface tywall {
    num:string,
    xh:string,
    std:string,
    name:string,
    width:string,
    size:string,
    start:string,
    end:string,
}

interface ban {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface ds {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface hnt {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
// interface dm {
//     name:string,
//     x1:number,
//     y1:number,
//     z1:number,
//     x2:number,
//     y2:number,
//     z2:number,
//     x3:number,
//     y3:number,
//     z3:number,
//     x4:number,
//     y4:number,
//     z4:number,
//     x5:number,
//     y5:number,
//     z5:number,
//     x6:number,
//     y6:number,
//     z6:number,
//     x7:number,
//     y7:number,
//     z7:number,
//     x8:number,
//     y8:number,
//     z8:number,
// }
interface qddk {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface jd {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    hei:number
}
interface fzq {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface qtdm {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface qtds {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface qtct {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface qddm {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface qdds {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}
interface qdct {
    name:string,
    x1:number,
    y1:number,
    z1:number,
    x2:number,
    y2:number,
    z2:number,
    x3:number,
    y3:number,
    z3:number,
    x4:number,
    y4:number,
    z4:number,
    x5:number,
    y5:number,
    z5:number,
    x6:number,
    y6:number,
    z6:number,
    x7:number,
    y7:number,
    z7:number,
    x8:number,
    y8:number,
    z8:number,
}

export type{
    tyBuilding,tybeam,tyslab,tywall,tycolumn,ban,ds,hnt,dm,jd,fzq,qddk,qtdm,qtds,qtct,qddm,qdds,qdct
}